networks:
  media_network:
    name: media_network
    driver: bridge
x-logging: &id001
  driver: json-file
  options:
    max-size: 10m
    max-file: '3'
services:
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}
    volumes:
    - ${CONFIG_DIR}/prowlarr:/config
    ports:
    - ${PORT_PROWLARR}:9696
    networks:
    - media_network
    restart: unless-stopped
    logging: *id001
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    depends_on:
    - qbittorrent
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}
    volumes:
    - ${CONFIG_DIR}/radarr:/config
    - /data/pool:/data:rshared
    ports:
    - ${PORT_RADARR}:7878
    networks:
    - media_network
    restart: unless-stopped
    logging: *id001
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    depends_on:
    - qbittorrent
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}
    volumes:
    - ${CONFIG_DIR}/sonarr:/config
    - /data/pool:/data:rshared
    ports:
    - ${PORT_SONARR}:8989
    networks:
    - media_network
    restart: unless-stopped
    logging: *id001
  recyclarr:
    image: ghcr.io/recyclarr/recyclarr:latest
    container_name: recyclarr
    env_file: .env
    environment:
    - PUID=${PUID}
    - PGID=${PGID}
    - TZ=${TZ}
    volumes:
    - ${CONFIG_DIR}/recyclarr:/config
    networks:
    - media_network
    restart: unless-stopped
    logging: *id001
  seerr:
    image: ghcr.io/seerr-team/seerr:latest
    container_name: seerr
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}
      LOG_LEVEL: info
    volumes:
    - ${CONFIG_DIR}/seerr:/app/config
    ports:
    - 5055:5055
    networks:
    - media_network
    restart: unless-stopped
    logging: *id001
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
    - PUID=${PUID}
    - PGID=${PGID}
    - TZ=${TZ}
    - JELLYFIN_PublishedServerUrl=http://localhost:8096
    volumes:
    - ${CONFIG_DIR}/jellyfin:/config
    - /data/pool:/data:ro
    ports:
    - ${PORT_JELLYFIN}:8096
    devices:
    - /dev/dri:/dev/dri
    networks:
    - media_network
    restart: unless-stopped
    logging: *id001
    group_add:
    - ${RENDER_GID}
  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    environment:
    - LOG_LEVEL=info
    - BROWSER_TIMEOUT=180000
    networks:
    - media_network
    restart: unless-stopped
    logging: *id001
    deploy:
      resources:
        limits:
          memory: 1G
    security_opt:
    - no-new-privileges:true
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    deploy:
      resources:
        limits:
          memory: 1024M
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}
      WEBUI_PORT: 8080
    volumes:
    - ${CONFIG_DIR}/qbittorrent:/config
    - /data/pool:/data:rshared
    ports:
    - ${PORT_QBIT}:8080
    - 6881:6881
    - 6881:6881/udp
    networks:
    - media_network
    restart: unless-stopped
    logging: *id001
  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}
    volumes:
    - ${CONFIG_DIR}/bazarr:/config
    - /data/pool:/data:rshared
    ports:
    - ${PORT_BAZARR}:6767
    networks:
    - media_network
    restart: unless-stopped
    logging: *id001
